Repository computer98400/gitcombantion, pull requests merged in 2022-02, with the labels that each got.

#16 add team
  team.txt
Labels: invalid

#45 Feature user
  README2.md
  newfile.txt
  readme.md
Labels: question

#47 text 폴더 생성
  readme.md
  test/text.txt
Labels: documentation

#43 feature/text.txt 추가
  readme.md
  text1.txt
Labels: bug

#46 Feature profile
  profile
  readme.md
Labels: documentation

#44 파일 추가했어요
  makefileagain
  maketestfile
  readme.md
Labels: help wanted

#48 머지좀 해주십사하고 올립니다
  newfile.txt
  test/text.txt
Labels: bug

#50 feature/profile
  newfile.txt
  text1.txt
Labels: bug

#49 feature/modify newfile, test
  newfile.txt
  test/text.txt
Labels: duplicate
